### PR TITLE
[FIX] Rating API Implementation

### PR DESCRIPTION
**Pull request by sandrex-SGV**
## Ticket/s

- [Rating v2 API implementation](https://trello.com/c/prWnoBYd/111-rating-api-implementation)

## Changes

- modify Create Rating API
- implementation of modified Create Rating API 
- fix modal bugs raised by QAs

## Screenshots

image

image

image

image

## How to test?

- run `pnpm run dev` script
- add to cart and checkout product 
- access http://localhost:5173/orders and rate ordered product

## Notes
- minor bugs to modal --- onChange data retains on modal of order with two products, to be fixed.

### CODE REVIEW

**Review by markjoshuacarmen — APPROVED** [review]
nice!

**Review by SGVGen — DISMISSED** [review]
` <StyledModal opened={isOpen} onClose={onClose} size="80%">`

Change `size="80%"` to `size="50%"`

**Review by TreshAnn — COMMENTED** [review]
image

Change the label to "Rating Description" instead of "Product Description." Also, it must have `handleCloseModal` so that the rating button will not appear when the user successfully creates a rating for an item.

**Comment by sandrex-SGV** [comment]
> ` <StyledModal opened={isOpen} onClose={onClose} size="80%">`
> 
> Change `size="80%"` to `size="50%"`

done sir

**Comment by sandrex-SGV** [comment]
> image
> 
> Change the label to "Rating Description" instead of "Product Description." Also, it must have `handleCloseModal` so that the rating button will not appear when the user successfully creates a rating for an item.

implemented close modal upon rating submission

**Review by TreshAnn — APPROVED** [review]
LGTM!

**Pull request merged**
