### PR TITLE
[API Integration] Update User

### PR DESCRIPTION
**Pull request by SGVGen**
## Ticket/s

- [Update User](https://trello.com/c/upwUHzYv/88-update-user)

## Changes

- Added updateUser API
- Added getOneUser API
- Added Update Form
- Added User Profile View

## Screenshot

- User - Profile

## How to test?

- run **pnpm dev**
- go to **/login**
- After Successful Login Attempt go to **/profile/:id**
- **/:id** can be seen in mongodb Compass

### CODE REVIEW

**Review by sandrex-SGV — COMMENTED** [review]
Updates every user info in User db.
Does not update Auth info.

**Review by TreshAnn — APPROVED** [review]
LGTM!

**Comment by markjoshuacarmen** [comment]
image
image

zip code allows letter

**Comment by SGVGen** [comment]
> image image
> 
> zip code allows letter

sir @markjoshuacarmen @5andrex You can try again with the testing.

**Comment by sandrex-SGV** [comment]
hello sir @SGVGen, input fields like last name, address, etc should accept spaces in between, Please see attached img. Thanks!

image

**Review by sandrex-SGV — APPROVED** [review]
LGTM

**Pull request merged**
