### PR TITLE
[Backend] Disable-Enable Product API

### PR DESCRIPTION
**Pull request by KezTimple**
## Ticket/s

- [Disable/Enable Product API](https://trello.com/b/FeFcZk4b/eycommerce)

## Changes

- Add disable/enable product API

## Screenshot

- Disable Product
image

- Enable Product
image

## How to test?

- Open Postman
- Log in User/Merchant
- Import cURL

**For Disable Product**
```
curl --location --globoff --request PUT 'localhost:3001/api/products/deactivateProduct/{insert ID}' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9tZWdhIiwic3ViIjoiNjRkMzA2NjhjZWI5YTExYjRiNzAxMWY4IiwiaWF0IjoxNjkxNTUxMzQ2LCJleHAiOjE2OTE2Mzc3NDZ9.h0M38IM9-JXrYvCqcffv71l4972WtGHwiys5XI2SKN8' \
--data ''
```
**For Enable Product**
```
curl --location --globoff --request PUT 'localhost:3001/api/products/activateProduct/{insert ID}' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9tZWdhIiwic3ViIjoiNjRkMzA2NjhjZWI5YTExYjRiNzAxMWY4IiwiaWF0IjoxNjkxNTUxMzQ2LCJleHAiOjE2OTE2Mzc3NDZ9.h0M38IM9-JXrYvCqcffv71l4972WtGHwiys5XI2SKN8 '
```
- Copy ID in MongoDB compass
- Put Auth in header-authorization
- Disable/Enable product by replacing the ID placeholders in the cURL above.
- Check in DB if the isActive field updates to true/false

### CODE REVIEW

**Comment by TreshAnn** [comment]
Hi, @KezTimple . I'm still unable to approve this PR. Please correct me if I'm mistaken, but according to the ticket, disabling a product renders it unavailable for purchase and hidden from customers. This implies that customers shouldn't be able to add or view this specific product.

**Review by brentmillen — CHANGES_REQUESTED** [review]
add a condition for read products function to check for the isActive field

**Comment by KezTimple** [comment]
> add a condition for read products function to check for the isActive field

done sir @brentmillen

**Review by brentmillen — APPROVED** [review]

**Review by TreshAnn — APPROVED** [review]
LGTM!

**Pull request merged**
