### PR TITLE
[Refactor] Big changes for ESLint and Web

### PR DESCRIPTION
**Pull request by DanDalanDone69**
## Ticket/s
-N/A

## Changes
- Remove NextJS and use custom React Framework Powered By Vite and SWC
- Update ESLint version and format all files

## Screenshot
image

### CODE REVIEW

**Review by TreshAnn — APPROVED** [review]
PR Approved! Everything looks fine, and the changes are working smoothly on my end.  Additionally, I'm planning to explore more documentation related to Vite and SWR.

**Review by markjoshuacarmen — COMMENTED** [review]
working on my end! will read some docs about this. tnx

**Review by markjoshuacarmen — APPROVED** [review]
working on my end! will read some docs about this. thanks

**Comment by brentmillen** [comment]
ran pnpm install successfully for this update

**Pull request merged**
