### PR TITLE
Fe/user review

### PR DESCRIPTION
**Pull request by ianchinjen**
## Ticket/s

- [FRONTEND: User Rating and Review Component](https://trello.com/c/0eVnkqKY/95-rating-component-user-review-and-rating)

## Changes

- Created a component for user rating and review.

## Screenshot

- image
- image
- image

## How to test?

- pnpm run dev

### CODE REVIEW

**Comment by SGVGen** [comment]
Hi sir @ianchinjen, I think it needs some padding or margins at the side.
image

**Comment by ianchinjen** [comment]
@SGVGen Hi sir gen, thanks for the comment, I think we can implement the padding and margin once we build the whole module of the user review and rating. Thank you.

**Review by sandrex-SGV — APPROVED** [review]
Working on my end. LGTM!

**Review by sandrex-SGV — CHANGES_REQUESTED** [review]
Hello Sir @ianchinjen, please see attached image.

image

This happens when I change the device as mobile in the dev tools.

**Review by TreshAnn — CHANGES_REQUESTED** [review]
Remove the `<section>` in sampleview.ts to fix overlapping components.

image

**Comment by ianchinjen** [comment]
Hello @TreshAnn and @5andrex, already applied the fix. Thank you.

**Review by TreshAnn — APPROVED** [review]

**Review by sandrex-SGV — APPROVED** [review]

**Review by markjoshuacarmen — APPROVED** [review]
nice!

**Pull request merged**
