### PR TITLE
Fix: Handle Negative Input in Modal

### PR DESCRIPTION
**Pull request by brentmillen**
## Ticket/s

- [83 - Product Modal](https://trello.com/c/646k9Pxa/83-display-available-products)

## Changes

- Add onKeyDown handler for stock and product price input fields
- Handler for ArrowDown when value of product price is 0

## Screenshot

- N/A

## How to test?

- login as merchant
- add/edit a product
- attempt input of (-) symbol

### CODE REVIEW

**Review by sandrex-SGV — APPROVED** [review]
LGTM!

**Review by SGVGen — APPROVED** [review]
LGTM!

**Review by TreshAnn — CHANGES_REQUESTED** [review]
Upon pressing down arrow key, the product price and inventory can be set to a negative value

image

image

**Comment by brentmillen** [comment]
> Upon pressing down arrow key, the product price and inventory can be set to a negative value
> 
> image
> 
> image

fixed in UI.

notes:
- API also needs to have a validation for negative values.
- Schema also needs to be updated to allow store of decimal for product price(currently in number format).

**Review by TreshAnn — APPROVED** [review]

**Pull request merged**
