### PR TITLE
[Backend] - Create Merchant API

### PR DESCRIPTION
**Pull request by TreshAnn**
## Ticket/s

-[Create Merchant API](https://trello.com/c/zEbayCQX)

## Changes

- Add Create Merchant API
- Modify Merchant Schema
- Add Create Merchant DTO
- Add Merchant Controller, Service and Module
- Add auth.schema and auth.dto
- Modify auth.service, auth.controller and auth.module

### Notes
-  Includes Password Hashing Feature
-  Please ensure that the `firstName` and `lastName` fields do not have any leading or trailing spaces.

#### Create Merchant
image

##### auths
image

##### merchants
image

#### via Postman cURL
- Open Postman
- click import tab, paste cURL
```
curl --location 'localhost:3001/merchant/create' \
--header 'Content-Type: application/json' \
--data-raw ' {
    "username": "sample",
    "email": "beta@email.com",
    "password": "SeCret!01",
    "userType": "merchant",
    "merchantName": "Merchant'\''s Shop",
    "firstName": "John Carlo",
    "lastName": "Dela cruz",
    "address": {
    "street": "123 Main Street",
    "city": "New York",
    "region": "NY",
    "zipcode": "10001",
    "country": "USA"
  },
  "phoneNumber": "+639212212121"

}'
```

### CODE REVIEW

**Review by markjoshuacarmen — APPROVED** [review]
LGTM!

**Review by dandalandone — APPROVED** [review]
LGTM

**Review by brentmillen — COMMENTED** [review]
unique shop name(merchant name) not yet implemented

merchantnamedups

**Review by dandalandone — DISMISSED** [review]
Move username, password, email to auth schema then reference it to merchants schema

**Review by sandrex-SGV — COMMENTED** [review]
Cannot have second name and space in firstName prop

image

**Comment by sandrex-SGV** [comment]
Please modify validation for phone number

image

**Comment by TreshAnn** [comment]
> unique shop name(merchant name) not yet implemented
> 
> merchantnamedups
Done. please check @brentmillen

**Comment by TreshAnn** [comment]
> Please modify validation for phone number
> 
> image
Done. please check @5andrex

**Comment by TreshAnn** [comment]
> Move username, password, email to auth schema then reference it to merchants schema

Done. please check sir @dandalandone

**Comment by brentmillen** [comment]
> > unique shop name(merchant name) not yet implemented
> > merchantnamedups
> > Done. please check @brentmillen

reviewed changes, working on my end

**Review by DanDalanDone69 — APPROVED** [review]

**Pull request merged**
